---
- name: "Boostrap the role {{ bootstrap_role__meta_role_name }}"
  block:
    - name: "Create folders"
      block:
        - name: "Create root/main directory"
          ansible.builtin.file:
            path: "{{ bootstrap_role__path }}"
            state: directory
            owner: "{{ bootstrap_role__user }}"
            group: "{{ bootstrap_role__user }}"
            mode: "0700"

        - name: "Create all sub directories"
          loop: "{{ bootstrap_role__folders }}"
          loop_control:
            loop_var: folder
          ansible.builtin.file:
            path: "{{ bootstrap_role__path }}/{{ folder }}"
            state: directory
            recurse: yes
            owner: "{{ bootstrap_role__user }}"
            group: "{{ bootstrap_role__user }}"
            mode: "0700"

        - name: "Create all molecule directories"
          loop: "{{ bootstrap_role__molecule_scenarios }}"
          loop_control:
            loop_var: scenario
          ansible.builtin.file:
            path: "{{ bootstrap_role__path }}/molecule/{{ scenario.name }}"
            state: directory
            recurse: yes
            owner: "{{ bootstrap_role__user }}"
            group: "{{ bootstrap_role__user }}"
            mode: "0700"

    - name: "Import main files"
      block:
        - name: "Import all README.md in directories"
          loop: "{{ bootstrap_role__folders }}"
          loop_control:
            loop_var: folder
          ansible.builtin.copy:
            src: "files/README.md"
            dest: "{{ bootstrap_role__path }}/{{ folder }}/README.md"
            owner: "{{ bootstrap_role__user }}"
            group: "{{ bootstrap_role__user }}"
            mode: "0700"

        - name: "Import all README.md in scenario"
          loop: "{{ bootstrap_role__molecule_scenarios }}"
          loop_control:
            loop_var: scenario
          ansible.builtin.copy:
            src: "files/README.md"
            dest: "{{ bootstrap_role__path }}/molecule/{{ scenario.name }}/README.md"
            owner: "{{ bootstrap_role__user }}"
            group: "{{ bootstrap_role__user }}"
            mode: "0700"

        - name: "Import all configuration files"
          loop: "{{ bootstrap__role_configuration_files }}"
          loop_control:
            loop_var: file
          ansible.builtin.copy:
            src: "files/{{ file }}"
            dest: "{{ bootstrap_role__path }}/{{ file }}"
            owner: "{{ bootstrap_role__user }}"
            group: "{{ bootstrap_role__user }}"
            mode: "0700"

        - name: "Import all main.yml files"
          loop: "{{ bootstrap_role__folders }}"
          loop_control:
            loop_var: folder
          vars:
            excluded_folders:
              - "molecule"
              - "templates"
              - "tests"
              - "tests/tower"
              - "tests/certs"
              - "tests/inventory"
              - "tests/inventory/group_vars"
              - "tests/inventory/host_vars"
              - "meta"
          when: folder not in excluded_folders
          ansible.builtin.copy:
            src: "files/main.yml"
            dest: "{{ bootstrap_role__path }}/{{ folder }}/main.yml"
            owner: "{{ bootstrap_role__user }}"
            group: "{{ bootstrap_role__user }}"
            mode: "0700"

    - name: "Template base elements for role {{ bootstrap_role__meta_role_name }}"
      loop:
        - { src: "templates/meta.yml.j2", dest: "{{ bootstrap_role__path }}/meta/main.yml" }
        - { src: "templates/README.md.j2", dest: "{{ bootstrap_role__path }}/README.md" }
        - { src: "templates/LICENCE.j2", dest: "{{ bootstrap_role__path }}/LICENCE" }
      loop_control:
        loop_var: file
      ansible.builtin.template:
        src: "{{ file.src }}"
        dest: "{{ file.dest }}"
        owner: "{{ bootstrap_role__user }}"
        group: "{{ bootstrap_role__user }}"
        mode: "0700"
        lstrip_blocks: yes

    - name: "Copy elements for inventory and testing for role {{ bootstrap_role__meta_role_name }}"
      loop:
        - { src: "files/tower.yml", dest: "{{ bootstrap_role__path }}/tests/tower/tower.yml" }
        - { src: "files/certs.yml", dest: "{{ bootstrap_role__path }}/tests/certs/main.yml" }
      loop_control:
        loop_var: file
      ansible.builtin.copy:
        src: "{{ file.src }}"
        dest: "{{ file.dest }}"
        owner: "{{ bootstrap_role__user }}"
        group: "{{ bootstrap_role__user }}"
        mode: "0700"

    - name: "Create Molecule scenarios (confs and inventory)"
      loop: "{{ bootstrap_role__molecule_scenarios }}"
      loop_control:
        loop_var: scenario
      ansible.builtin.include_tasks:
        file: "create_scenario.yml"

    - name: "Template inventory hosts file for role {{ bootstrap_role__meta_role_name }}"
      ansible.builtin.template:
        src: "templates/hosts.yml.j2"
        dest: "{{ bootstrap_role__path }}/tests/inventory/hosts.yml"
        owner: "{{ bootstrap_role__user }}"
        group: "{{ bootstrap_role__user }}"
        mode: "0700"
        lstrip_blocks: yes

    - name: "Template inventory groups files for role {{ bootstrap_role__meta_role_name }}"
      when: bootstrap_role__inventory_groups | default(false)
      loop: "{{ bootstrap_role__inventory_groups }}"
      loop_control:
        loop_var: group
      ansible.builtin.template:
        src: "files/main.yml"
        dest: "{{ bootstrap_role__path }}/tests/inventory/group_vars/{{ group }}.yml"
        owner: "{{ bootstrap_role__user }}"
        group: "{{ bootstrap_role__user }}"
        mode: "0700"
        lstrip_blocks: yes

    - name: "Copy main.yaml for all.yml"
      ansible.builtin.copy:
        src: "files/main.yml"
        dest: "{{ bootstrap_role__path }}/tests/inventory/group_vars/all.yml"
        owner: "{{ bootstrap_role__user }}"
        group: "{{ bootstrap_role__user }}"
        mode: "0700"
