# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
- gitlab-test
- lint
- sonarqube-check
- molecule
- publish

###############################################################################
#################### actions
###############################################################################

variables:
  ANSIBLE_FORCE_COLOR: "true"
  PY_COLORS: "1"
  #
  SONAR_HOST_URL: "$SONARQUBE_ADDRESS"
  SONAR_TOKEN: "$GITLAB_CI_SONARQUBE_USER_TOKEN"
  #
  DOCKER_IMAGE__ANALYSE_SONAR_SCANNER: "labocbz/analyse-sonar-scanner:latest"
  DOCKER_IMAGE__LINT_SECRETS: "labocbz/lint-secrets:latest"
  DOCKER_IMAGE__LINT_ANSIBLE: "labocbz/lint-ansible:latest"
  DOCKER_IMAGE__LINT_YAML: "labocbz/lint-yaml:latest"
  DOCKER_IMAGE__LINT_JINJA: "labocbz/lint-jinja:latest"
  DOCKER_IMAGE__LINT_MARKDOWN: "labocbz/lint-markdown:latest"
  DOCKER_IMAGE__RUN_SSH: "labocbz/run-ssh:latest"
  DOCKER_IMAGE__RUN_ANSIBLE_MOLECULE: "labocbz/run-ansible-molecule:latest"
  DOCKER_IMAGE__PUBLISH_GITLAB_RELEASE: "labocbz/publish-gitlab-release:latest"
  DOCKER_IMAGE__ANSIBLETEST_DEBIAN_11: "labocbz/ansibletest-debian-11:latest"
  DOCKER_IMAGE__ANSIBLETEST_DEBIAN_12: "labocbz/ansibletest-debian-12:latest"
  DOCKER_IMAGE__ANSIBLETEST_UBUNTU_22: "labocbz/ansibletest-ubuntu-22:latest"
  DOCKER_IMAGE__ANSIBLETEST_DOCKER_DIND: "labocbz/ansibletest-docker-dind:latest"

###############################################################################
#################### EXTENDABLES
###############################################################################

.molecule_test: &molecule_test
  image: $NEXUS_DOCKER_GROUP_REGISTRY/$DOCKER_IMAGE__RUN_ANSIBLE_MOLECULE
  stage: molecule
  before_script:
    - "export DOCKER_CLIENT_TIMEOUT=180"
    - "export COMPOSE_HTTP_TIMEOUT=180"
    - "docker login -u \"$NEXUS_REPOS_USERNAME\" -p \"$NEXUS_REPOS_PASSWORD\" \"http://$NEXUS_DOCKER_GROUP_REGISTRY\""
    - "python3 -m compileall /usr/lib/python3 -qq"
    - "cp ./.ansible.cfg /root/.ansible.cfg"
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
    - "[ -f \"./molecule/$SCENARIO/requirements.yml\" ] && ansible-galaxy install -r ./molecule/$SCENARIO/requirements.yml --roles-path=./molecule/$SCENARIO/roles"
  script:
    - "molecule test --scenario-name $SCENARIO"
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_MESSAGE=~/^[^Merge]/ && $CI_COMMIT_BRANCH == "develop"'
  needs:
    - "lint:yaml"
    - "lint:jinja"
    - "lint:ansible"

###############################################################################
#################### CICD
###############################################################################

# As a GitLab ci, we use the default template :)
sast:
  stage: gitlab-test
include:
- template: Security/SAST.gitlab-ci.yml

lint:yaml:
  stage: lint
  image: $NEXUS_DOCKER_GROUP_REGISTRY/$DOCKER_IMAGE_YAML_LINT
  before_script:
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
  script:
    - yamllint --list-files ./
    - yamllint -c ./.yamllint ./
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_MESSAGE=~/^[^Merge]/ && $CI_COMMIT_BRANCH == "develop"'

lint:jinja:
  stage: lint
  image: $NEXUS_DOCKER_GROUP_REGISTRY/$DOCKER_IMAGE_JINJA_LINT
  before_script:
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
  script:
    - "[ -n \"$(find ./templates -name '*.j2')\" ] && j2lint ./templates/*.j2 --ignore S3 S7"
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_MESSAGE=~/^[^Merge]/ && $CI_COMMIT_BRANCH == "develop"'

lint:ansible:
  stage: lint
  image: $NEXUS_DOCKER_GROUP_REGISTRY/$DOCKER_IMAGE_ANSIBLE_LINT
  before_script:
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
  script:
    - ansible-lint --config=./.ansible-lint --exclude molecule --exclude tests ./*
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_MESSAGE=~/^[^Merge]/ && $CI_COMMIT_BRANCH == "develop"'

lint:markdown:
  stage: lint
  image: $NEXUS_DOCKER_GROUP_REGISTRY/$DOCKER_IMAGE__LINT_MARKDOWN
  before_script:
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
  script:
    - markdownlint './README.md' --disable MD013
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_MESSAGE=~/^[^Merge]/ && $CI_COMMIT_BRANCH == "develop"'

molecule:test-debian-12:
  <<: *molecule_test
  variables:
    SCENARIO: "cicd-debian-12"
  rules:
    - if: '$CI_COMMIT_MESSAGE=~/^[^Merge]/ && $CI_COMMIT_BRANCH == "develop"'

molecule:test-ubuntu-22:
  <<: *molecule_test
  variables:
    SCENARIO: "cicd-ubuntu-22"
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_MESSAGE=~/^[^Merge]/ && $CI_COMMIT_BRANCH == "develop"'

molecule:test-debian-11:
  <<: *molecule_test
  variables:
    SCENARIO: "cicd-debian-11"
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_MESSAGE=~/^[^Merge]/ && $CI_COMMIT_BRANCH == "develop"'

publish:release-candidate:
  image: $NEXUS_DOCKER_GROUP_REGISTRY/$DOCKER_IMAGE__RUN_SSH
  stage: publish
  variables:
    CI_JOB_TOKEN: $CICD_TOKEN
  allow_failure: false
  before_script:
    - "REMOTE_ADDRESS=$(echo \"$CI_REPOSITORY_URL\" | awk -F@ '{print $2}' | sed 's|/|:|')"
    - "TIMESTAMP=$(date +'%Y.%m.%d-%H.%M.%S')"
    - "TAGS=$(git ls-remote --tags origin | awk '{print $2}' | grep -oE 'refs/tags/[0-9.]+' | cut -d '/' -f 3 | sort -V)"
    - "LATEST_TAG=$(echo \"$TAGS\" | tail -n 1)"
    - "VERSION=$(echo \"$LATEST_TAG\" | grep -oE '^[0-9]+') && VERSION=$((VERSION + 1))"
    - "RC_BRANCH_NAME=\"RC-$VERSION-$TIMESTAMP\""
    #
    - "mkdir -p ~/.ssh"
    - "echo \"$(cat $GITLAB_CI_SSH_PRIVATE_KEY)\" | tr -d '\r' > ~/.ssh/id_rsa"
    - "echo \"$(cat $GITLAB_CI_SSH_PUBLIC_KEY)\" | tr -d '\r' > ~/.ssh/id_rsa.pub"
    - "chmod 400 ~/.ssh/id_rsa*"
    - "eval \"$(ssh-agent -s)\""
    - "ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts"
  script:
    - "git config user.email \"$GITLAB_USER_EMAIL\""
    - "git config user.name \"$GITLAB_USER_EMAIL\""
    - "git remote remove r_origin || true"
    - "git remote add r_origin git@$REMOTE_ADDRESS"
    - "git checkout \"develop\""
    - "git stash"
    - "git pull origin \"develop\""
    - "git checkout -b \"$RC_BRANCH_NAME\""
    - "git add ."
    - "git push r_origin \"$RC_BRANCH_NAME\""
  needs:
    - "molecule:test-debian-12"
    - "sonarqube-check"
  rules:
    - if: '$CI_COMMIT_MESSAGE=~/^[^Merge]/ && $CI_COMMIT_BRANCH == "develop"'

sonarqube-check:
  stage: sonarqube-check
  image: 
    name: $NEXUS_DOCKER_GROUP_REGISTRY/$DOCKER_IMAGE_SONAR_SCANNER_CLI
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - ".sonar/cache"
  script: 
    - "sonar-scanner"
  rules:
    - if: '$CI_COMMIT_MESSAGE=~/^[^Merge]/ && $CI_COMMIT_BRANCH == "develop"'
    - if: '$CI_COMMIT_BRANCH == "main"'

publish:set-artefact-version:
  image: $NEXUS_DOCKER_GROUP_REGISTRY/$DOCKER_IMAGE__RUN_SSH
  stage: publish
  before_script:
    - "TAGS=$(git ls-remote --tags origin | awk '{print $2}' | grep -oE 'refs/tags/[0-9.]+' | cut -d '/' -f 3 | sort -V)"
    - "LATEST_TAG=$(echo \"$TAGS\" | tail -n 1)"
    - "VERSION=$(echo \"$LATEST_TAG\" | grep -oE '^[0-9]+') && VERSION=$((VERSION + 1))"
  script:
    - "echo \"RELEASE $VERSION from latest RC-$VERSION\""
    - "echo \"VERSION=$VERSION\" >> VERSION.env"
  artifacts:
    reports:
      dotenv: VERSION.env
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  needs:
    - "sonarqube-check"

publish:release:
  image: $NEXUS_DOCKER_GROUP_REGISTRY/$DOCKER_IMAGE__PUBLISH_GITLAB_RELEASE
  stage: publish
  script:
    - "echo \"RELEASE $VERSION from latest RC-$VERSION\""
  release:
    name: "$VERSION"
    description: "RELEASE $VERSION from latest RC-$VERSION"
    tag_name: "$VERSION"
    ref: "$CI_COMMIT_SHA"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  needs:
    - job: "publish:set-artefact-version"
      artifacts: true
